name: AirPort

on:
  push:
    branches:
      - main
  # manual run
  workflow_dispatch:
    inputs:

jobs:
  airport:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Repo Directory
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Docker Login
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Start SSH
        run: ./airport/github-action-ssh.sh
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USER_PASS: ${{ secrets.USER_PASS }}

      - name: Sync Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "airport is triggerd"

      - name: Don't kill instace
        run: sleep 30m # Prevent to killing instance
